### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RobHayward** [MHohenberg/ical2paleventfile#5]
Hi Martin, 

I spoke to you a while ago about setting up my calendars and everything was working fine (and still is for some machines).  However, for one I have the following error.  I have tried reinstalling but that does not solve the issue.  The error that I have is

```
url: https://calendar.google.com/calendar/ical/robohay%40gmail.com/private-3dbda6130d9a25dd38d5ef3ac13755d8/basic.ics
pal: /home/rob/.pal/myfile.pal
calendar name: MC MyCalendar
UnicodeEncodeError
UnicodeEncodeError
UnicodeEncodeError
UnicodeEncodeError
UnicodeEncodeError
Traceback (most recent call last):
  File "/home/rob/bin/ical2paleventfileSTOP", line 36, in <module>
    url = parser.get(section, "url")
  File "/usr/lib/python2.7/ConfigParser.py", line 623, in get
    return self._interpolate(section, option, value, d)
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 732, in _interpolate_some
    "'%%' must be followed by '%%' or '(', found: %r" % (rest,))
ConfigParser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2FLondon'
```
This suggests something about the characters but that does not make sense to me because it works on another machine.

**Comment by MrConorAE** [comment]
I believe you need to escape percent characters in the URL by putting another percent character after them; e.g. `%2FLondon` should become `%%2FLondon`.
